groups:
  - name: http_request_duration.rules
    interval: 30s
    rules:
      - record: handler_instance:prometheus_http_request_duration_seconds_sum:rate5m
        expr: >
          rate(prometheus_http_request_duration_seconds_sum[5m])
      
      - record: handler_instance:prometheus_http_request_duration_seconds_count:rate5m
        expr: >
          rate(prometheus_http_request_duration_seconds_count[5m])
      
      - record: handler:prometheus_http_request_duration_seconds:mean5m
        expr: >
          sum without (instance) (
            handler_instance:prometheus_http_request_duration_seconds_sum:rate5m
          )
          /
          sum without (instance) (
            handler_instance:prometheus_http_request_duration_seconds_count:rate5m
          )